### ISSUE TITLE
Build binaries using CI pipeline

### ISSUE THREAD

**Issue by charlysan** [mlorenzati/pico-rgb2hdmi#32]
I've created a Github Action [pipeline](https://github.com/charlysan/pico-rgb2hdmi/blob/test-pipeline/.github/workflows/pipeline.yml) that can build the firmware for pico using a Docker container, and then upload the binaries as an asset within a release:

<img width="1228" alt="image" src="https://github.com/mlorenzati/pico-rgb2hdmi/assets/12597670/28d0dddd-9507-4003-9fa1-dab80bf8b088">

<img width="716" alt="image" src="https://github.com/mlorenzati/pico-rgb2hdmi/assets/12597670/e4059b8c-30f0-4ef7-8961-9f4cca609c09">

The pipeline gets triggered only when a new tag is created, and the assets will be uploaded to that release.

If you like this approach, I can push a Pull Request from my fork.

**Comment by mlorenzati** [comment]
Of course @charlysan that's an excellent collaboration, share the PR and I will review it
